* Build
Generate:
~rm -rf _build ; mkdir _build ; cmake . -B _build -DCMAKE_EXPORT_COMPILE_COMMANDS=1~

If you want to use some other compiler, e.g. clang, pass these options
to cmake: ~-DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang~

Build:
~cmake --build _build~

** Not the freshest Linux distro
Take for example Ubuntu 22, which has the following issues:
1. llvm in package manager is very outdated
2. C++ compiler is also quite outdated, and doesn't support
   e.g. std::expected

The 1st problem can be solved by llvm provided script to install fresh
version:

~sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"~

Ah, the safe and reliable wget2sudo, my beloved.

The 2nd one is partially solved by the 1st step leaving us with a
modern clang, but there's also an issue of libstdc++ expecting
different language macro values than libc++ would have, specifically,
we need ~__cpp_concepts~ to be defined with value >=202002L in order
for std::expected to work. Thus, to correctly configure Fulcrum for
building, the following CMake command shall be used:
#+begin_src
cmake . -B _build -DCMAKE_EXPORT_COMPILE_COMMANDS=1
-DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_C_COMPILER=clang-18
-DCMAKE_CXX_FLAGS="-D__cpp_concepts=202412L
-Wno-builtin-macro-redefined" -DLLVM_CONFIG_BIN=llvm-config-18
#+end_src

*** Debugging
Don't forget to pass ~-glldb~ if you want to debug the resulting
executable with lldb. Otherwise it will be unpleasant: incomplete
types, failures to find certain symbols and so on.

** Macos
Don't forget to export paths to LLVM and Clang:
~export LLVM_DIR=/opt/homebrew/Cellar/llvm/14.0.6_1/lib/cmake/llvm~
~export Clang_DIR=/opt/homebrew/Cellar/llvm/14.0.6_1/lib/cmake/clang~

* Debug
** Parser
There's ~Parser::Expression::dump()~ method, which is intended to be
used in situations where there's a need to inspect AST more closely.
Use it like this:
#+begin_src
bool SemanticAnalyzer::run(Parser &_parser) {
    parser = &_parser;

    auto tree = parser->releaseSyntaxTree();
+    tree->dump();
#+end_src

* Language
** Module declaration
*** Syntax
#+begin_src
(module module-name
   (import some-module)
   (import :c "stdio.h")
   (import :c "SDL2/SDL.h"))
   (import other-module :as nickname)
#+end_src

Imports with nicknames are imported as ~nickname.symbol_name~.
Imports without nicknames are prefixed as module name.

Names from C imports are imported directly inside the module.

** Function definitions
#+begin_src
(fn function-name ret-type ((arg-1 arg-1-type) (arg-2 arg-2-type))
fn-body)
#+end_src

** Variable declaration
#+begin_src
(var name type [initial value])
#+end_src

** Structures
(struct name
  (field-1-name type-1)
  (field-2-name type-2))
